config/urls.py
from django.contrib import admin
from django.urls import path, include
from dbconn.views import index

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('dbconn/', include('dbconn.urls', namespace="dbconn")),
    path('report/', include('report.urls', namespace="report")),
]

dbconn/urls.py
from django.urls import path
from . import views

app_name = 'dbconn'

urlpatterns = [
    path('create/', views.create_chart, name='create_chart'),
    path('history/', views.HistoryAPIView.as_view(), name='history_list')
]

report/urls.py
from django.urls import path
from . import views

app_name = 'report'

urlpatterns = [
    path('', views.report, name='index'),
    path('dbinfo/<int:history_id>/', views.get_dbinfo_report, name='report'),
    path('major/<int:history_id>/', views.get_major_top_10_report, name='major_top'),
    path('sqlstat-only/<int:history_id>/', views.get_sql_stat_sql_only_report, name='sql_stat_only'),

]

dbconn/models.py
from django.db import models


class DBconn(models.Model):

    username = models.CharField( max_length=50)
    password = models.CharField( max_length=50)
    server_ip = models.CharField( max_length=50)
    port = models.IntegerField()
    sid = models.CharField(default="TEST", max_length=50)

    def __str__(self):
        return f'{self.username} - {self.server_ip}:{self.port}'

class History(models.Model):

    db_conn = models.ForeignKey(DBconn, on_delete=models.CASCADE)
    start_date = models.CharField( max_length=50)
    end_date = models.CharField( max_length=50)
    instance_number = models.IntegerField(default=1)

    def __str__(self):
        return f'{self.db_conn} / {self.start_date[:-4]} ~ {self.end_date[:-4]}'

    def get_db_conn(self):
        return self.db_conn

report/models.py
from django.db import models
from dbconn.models import History


class DBInfoReport(models.Model):

    history = models.ForeignKey(History, on_delete=models.CASCADE)
    ftype = models.CharField(max_length=200, null=True)
    name = models.CharField(max_length=200, null=True) 
    value = models.CharField(max_length=200, null=True)
    note = models.CharField(max_length=200, null=True)


class MajorTop10Report(models.Model):

    history = models.ForeignKey(History, on_delete=models.CASCADE)
    snap_time = models.CharField(max_length=50, null=True)
    value_per_sec_1 = models.CharField(max_length=50, null=True)
    value_per_sec_2 = models.CharField(max_length=50, null=True)
    value_per_sec_3 = models.CharField(max_length=50, null=True)
    value_per_sec_4 = models.CharField(max_length=50, null=True)
    value_per_sec_5 = models.CharField(max_length=50, null=True)
    value_per_sec_6 = models.CharField(max_length=50, null=True)
    value_per_sec_7 = models.CharField(max_length=50, null=True)
    value_per_sec_8 = models.CharField(max_length=50, null=True)
    value_per_sec_9 = models.CharField(max_length=50, null=True)
    value_per_sec_10 = models.CharField(max_length=50, null=True)
    value_per_sec_etc = models.CharField(max_length=50, null=True)
    value_diff_1 = models.CharField(max_length=50, null=True)
    value_diff_2 = models.CharField(max_length=50, null=True)
    value_diff_3 = models.CharField(max_length=50, null=True)
    value_diff_4 = models.CharField(max_length=50, null=True)
    value_diff_5 = models.CharField(max_length=50, null=True)
    value_diff_6 = models.CharField(max_length=50, null=True)
    value_diff_7 = models.CharField(max_length=50, null=True)
    value_diff_8 = models.CharField(max_length=50, null=True)
    value_diff_9 = models.CharField(max_length=50, null=True)
    value_diff_10 = models.CharField(max_length=50, null=True)
    value_diff_etc = models.CharField(max_length=50, null=True)


class SQLStatSQLOnlyReport(models.Model):

    history = models.ForeignKey(History, on_delete=models.CASCADE)
    viewtype = models.CharField(max_length=50, null=True)
    sql_id = models.CharField(max_length=50, null=True)
    optimizer_mode = models.CharField(max_length=50, null=True)
    module = models.CharField(max_length=50, null=True)
    executions = models.CharField(max_length=50, null=True)
    fetches = models.CharField(max_length=50, null=True)
    sorts = models.CharField(max_length=50, null=True)
    buffer_gets = models.CharField(max_length=50, null=True)
    disk_reads = models.CharField(max_length=50, null=True)
    rows_processed = models.CharField(max_length=50, null=True)
    cpu_time = models.CharField(max_length=50, null=True)
    elapsed_time = models.CharField(max_length=50, null=True)
    buf_exec = models.CharField(max_length=50, null=True)
    disk_exec = models.CharField(max_length=50, null=True)
    rows_exec = models.CharField(max_length=50, null=True)
    cpu_exec = models.CharField(max_length=50, null=True)
    elap_exec = models.CharField(max_length=50, null=True)
    iowait = models.CharField(max_length=50, null=True)
    clwait = models.CharField(max_length=50, null=True)
    apwait = models.CharField(max_length=50, null=True)
    ccwait = models.CharField(max_length=50, null=True)
    rnum = models.CharField(max_length=50, null=True)
    sql_text = models.TextField(null=True)
    sql_plan = models.TextField(null=True)
    plan_cost1 = models.CharField(max_length=50, null=True)
    plan_cost2 = models.CharField(max_length=50, null=True)
    bind_value = models.CharField(max_length=50, null=True)
    sql_profile = models.CharField(max_length=50, null=True)

dbconn/forms.py
from django import forms
from .models import DBconn, History

class DBconnForm(forms.ModelForm):
    class Meta:
        model = DBconn
        fields = ('username', 'password', 'server_ip', 'port')

# class HistoryForm(forms.ModelForm):
#     class Meta:
#         model = History
#         field = 

dbconn/views.py
from django.core import serializers
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.http import require_POST, require_GET

from rest_framework.decorators import api_view
from rest_framework.views import APIView
from rest_framework.response import Response

from util.database import managers
from util.decorators import ajax_required
from .forms import DBconnForm
from .models import DBconn, History
from .serializers import HistorySerializer 

def index(request):
    taplate_name = 'index.html'
    return render(request, taplate_name)


class HistoryAPIView(APIView):

    def get(self, request, format=None):
        history_list = History.objects.all()
        serializer = HistorySerializer(history_list, many=True)
        return Response(serializer.data)

@ajax_required
@api_view(['POST'])
def create_chart(request):
    username = request.POST['username']
    password = request.POST['password']
    server_ip = request.POST['server_ip']
    port = request.POST['port']
    
    # start_date = request.POST['start_date']
    start_date = "201907150000" 
    # end_date = request.POST['end_date']
    end_date = "201907150100"

    history = History.objects.get_or_create(db_conn=DBconn.objects.get(pk=2), 
                                  start_date=start_date,
                                  end_date=end_date)[0]
    
    dbmanager = managers.ConnectionManager(history)
    
    # if connection is right, exeute creating chart.    
    # dbmanager.exeute()
    # else return alert Wrong wanning.
    serializer = HistorySerializer(history)
    return Response(serializer.data)

report/views.py
from django.shortcuts import render
from rest_framework.decorators import api_view
from rest_framework.views import APIView
from rest_framework.response import Response

from util.decorators import ajax_required
from .models import DBInfoReport, SQLStatSQLOnlyReport, MajorTop10Report

def report(request):
    taplate_name = 'dbconn/report.html'
    return render(request, taplate_name)

@ajax_required
@api_view(['GET'])
def get_dbinfo_report(request, history_id):
    db_info_report_list = DBInfoReport.objects.filter(history__id=history_id)
    ftype = []
    name = []
    value = []
    note = []

    for db_info_report in db_info_report_list:
        ftype.append(db_info_report.ftype)
        name.append(db_info_report.name)
        value.append(db_info_report.value)
        note.append(db_info_report.note)
    
    data = {
        "ftype" : ftype,
        "name" : name,
        "value" : value,
        "note" : note
    }
    return Response(data)

@ajax_required
@api_view(['GET'])
def get_major_top_10_report(request, history_id):
    major_top_10_report_list = MajorTop10Report.objects.filter(history__id=history_id)
    snap_time = []
    value_per_sec_1 = []
    value_per_sec_2 = []
    value_per_sec_3 = []
    value_per_sec_4 = []
    value_per_sec_5 = []
    value_per_sec_6 = []
    value_per_sec_7 = []
    value_per_sec_8 = []
    value_per_sec_9 = []
    value_per_sec_10 = []
    value_per_sec_etc = []
    value_diff_1 = []
    value_diff_2 = []
    value_diff_3 = []
    value_diff_4 = []
    value_diff_5 = []
    value_diff_6 = []
    value_diff_7 = []
    value_diff_8 = []
    value_diff_9 = []
    value_diff_10 = []
    value_diff_etc = []

    for major_top_10_report in major_top_10_report_list:
        snap_time.append(major_top_10_report.snap_time)
        value_per_sec_1.append(major_top_10_report.value_per_sec_1)
        value_per_sec_2.append(major_top_10_report.value_per_sec_2)
        value_per_sec_3.append(major_top_10_report.value_per_sec_3)
        value_per_sec_4.append(major_top_10_report.value_per_sec_4)
        value_per_sec_5.append(major_top_10_report.value_per_sec_5)
        value_per_sec_6.append(major_top_10_report.value_per_sec_6)
        value_per_sec_7.append(major_top_10_report.value_per_sec_7)
        value_per_sec_8.append(major_top_10_report.value_per_sec_8)
        value_per_sec_9.append(major_top_10_report.value_per_sec_9)
        value_per_sec_10.append(major_top_10_report.value_per_sec_10)
        value_per_sec_etc.append(major_top_10_report.value_per_sec_etc)
        value_diff_1.append(major_top_10_report.value_diff_1)
        value_diff_2.append(major_top_10_report.value_diff_2)
        value_diff_3.append(major_top_10_report.value_diff_3)
        value_diff_4.append(major_top_10_report.value_diff_4)
        value_diff_5.append(major_top_10_report.value_diff_5)
        value_diff_6.append(major_top_10_report.value_diff_6)
        value_diff_7.append(major_top_10_report.value_diff_7)
        value_diff_8.append(major_top_10_report.value_diff_8)
        value_diff_9.append(major_top_10_report.value_diff_9)
        value_diff_10.append(major_top_10_report.value_diff_10)
        value_diff_etc.append(major_top_10_report.value_diff_etc)
    
    data = {
        "snap_time" : snap_time,
        "value_per_sec_1" : value_per_sec_1,
        "value_per_sec_2" : value_per_sec_2,
        "value_per_sec_3" : value_per_sec_3,
        "value_per_sec_4" : value_per_sec_4,
        "value_per_sec_5" : value_per_sec_5,
        "value_per_sec_6" : value_per_sec_6,
        "value_per_sec_7" : value_per_sec_7,
        "value_per_sec_8" : value_per_sec_8,
        "value_per_sec_9" : value_per_sec_9,
        "value_per_sec_10" : value_per_sec_10,
        "value_per_sec_etc" : value_per_sec_etc,
        "value_diff_1" : value_diff_1,
        "value_diff_2" : value_diff_2,
        "value_diff_3" : value_diff_3,
        "value_diff_4" : value_diff_4,
        "value_diff_5" : value_diff_5,
        "value_diff_6" : value_diff_6,
        "value_diff_7" : value_diff_7,
        "value_diff_8" : value_diff_8,
        "value_diff_9" : value_diff_9,
        "value_diff_10" : value_diff_10,
        "value_diff_etc" : value_diff_etc
    }
    return Response(data)

@ajax_required
@api_view(['GET'])
def get_sql_stat_sql_only_report(request, history_id):
    sql_stat_sql_only_list = SQLStatSQLOnlyReport.objects.filter(history__id=history_id)
    viewtype = [] 
    sql_id = [] 
    optimizer_mode = [] 
    module = [] 
    executions = [] 
    fetches = [] 
    sorts = [] 
    buffer_gets = [] 
    disk_reads = [] 
    rows_processed = [] 
    cpu_time = [] 
    elapsed_time = [] 
    buf_exec = [] 
    disk_exec = [] 
    rows_exec = [] 
    cpu_exec = [] 
    elap_exec = [] 
    iowait = [] 
    clwait = [] 
    apwait = [] 
    ccwait = [] 
    rnum = [] 
    sql_text = [] 
    sql_plan = [] 
    plan_cost1 = [] 
    plan_cost2 = [] 
    bind_value = [] 
    sql_profile = [] 

    for sql_stat_sql_only in sql_stat_sql_only_list:
        viewtype.append(sql_stat_sql_only.viewtype) 
        sql_id.append(sql_stat_sql_only.sql_id) 
        optimizer_mode.append(sql_stat_sql_only.optimizer_mode) 
        module.append(sql_stat_sql_only.module) 
        executions.append(sql_stat_sql_only.executions) 
        fetches.append(sql_stat_sql_only.fetches) 
        sorts.append(sql_stat_sql_only.sorts) 
        buffer_gets.append(sql_stat_sql_only.buffer_gets) 
        disk_reads.append(sql_stat_sql_only.disk_reads) 
        rows_processed.append(sql_stat_sql_only.rows_processed) 
        cpu_time.append(sql_stat_sql_only.cpu_time) 
        elapsed_time.append(sql_stat_sql_only.elapsed_time) 
        buf_exec.append(sql_stat_sql_only.buf_exec) 
        disk_exec.append(sql_stat_sql_only.disk_exec) 
        rows_exec.append(sql_stat_sql_only.rows_exec) 
        cpu_exec.append(sql_stat_sql_only.cpu_exec) 
        elap_exec.append(sql_stat_sql_only.elap_exec) 
        iowait.append(sql_stat_sql_only.iowait) 
        clwait.append(sql_stat_sql_only.clwait) 
        apwait.append(sql_stat_sql_only.apwait) 
        ccwait.append(sql_stat_sql_only.ccwait) 
        rnum.append(sql_stat_sql_only.rnum) 
        sql_text.append(sql_stat_sql_only.sql_text) 
        sql_plan.append(sql_stat_sql_only.sql_plan) 
        plan_cost1.append(sql_stat_sql_only.plan_cost1) 
        plan_cost2.append(sql_stat_sql_only.plan_cost2) 
        bind_value.append(sql_stat_sql_only.bind_value) 
        sql_profile.append(sql_stat_sql_only.sql_profile) 
    
    data = {
        "viewtype" : viewtype, 
        "sql_id" : sql_id, 
        "optimizer_mode" : optimizer_mode, 
        "module" : module, 
        "executions" : executions, 
        "fetches" : fetches, 
        "sorts" : sorts, 
        "buffer_gets" : buffer_gets, 
        "disk_reads" : disk_reads, 
        "rows_processed" : rows_processed, 
        "cpu_time" : cpu_time, 
        "elapsed_time" : elapsed_time, 
        "buf_exec" : buf_exec, 
        "disk_exec" : disk_exec, 
        "rows_exec" : rows_exec, 
        "cpu_exec" : cpu_exec, 
        "elap_exec" : elap_exec, 
        "iowait" : iowait, 
        "clwait" : clwait, 
        "apwait" : apwait, 
        "ccwait" : ccwait, 
        "rnum" : rnum, 
        "sql_text" : sql_text, 
        "sql_plan" : sql_plan, 
        "plan_cost1" : plan_cost1, 
        "plan_cost2" : plan_cost2, 
        "bind_value" : bind_value, 
        "sql_profile" : sql_profile
    }
    return Response(data)

dbconn/templates/dbconn/report.html
{% extends "base.html" %}

{% block content %}
<div>
  <canvas id="myChart" width="1000" height="700"></canvas>
  <button id="sendAjax">button</button>
</div>
{% endblock %}

<script>
{% block domready %}
$.ajax({
  type: "GET",
  url: "{% url 'report:major_top' history_id=5 %}",
  success: function(report){
    const ctx = document.getElementById("myChart").getContext('2d');                                           
    console.log(report, data, options)
    var data = {
      labels: report.snap_time,
      datasets: [
        {
          label: 'OJVM: Generic/Sec', 
          data: report.value_per_1,
          backgroundColor: [
                  'rgba(255, 99, 132, 0.2)',
                ],
          borderColor: [
                  'rgba(255,99,132,1)',
                ],
          borderWidth: 1
        },
        {
          label: 'db file scattered red/Sec',
          data: [
                  0.776, 0.001, 0, 0.259
                ],
          backgroundColor: [
                  'rgba(54, 162, 235, 0.2)',
                ],
        },
        {
          label: 'Backup: MML create a backup piece/Sec',
          data: [
                  0, 0.063, 0.535, 0.199
                ],
          backgroundColor: [
                'rgba(255, 206, 86, 0.2)',
                ],
        }
      ]
    };
    const myLinechart = new Chart(ctx, {
                    type: 'pie',
                    data: data,
                    options: options
                  });
  },
  error: function(error){
    console.log("error");
    console.log(error);
  }
})
var options = {
    animation: {
      animateScale: true
      },
    responsive: false,
    scales: {
      yAxes: [
        {
          ticks: {
            beginAtZero: true                                                                    
          }
        }
      ]
    }
  };

// function sendAjax(url) {
//     var oReq = new XMLHttpRequest();
 
//     oReq.open('POST', url);
//     oReq.setRequestHeader('Content-Type', "application/json") // json 형태로 보낸다                         
//     oReq.send();
 
//     oReq.addEventListener('load', function() {
//         var result = JSON.parse(oReq.responseText);
//         var score = result.score;
//         var comp_data = data.datasets[0].data;
 
//         for (var i = 0; i < comp_data.length; i++) {
//             comp_data[i] = score[i];
//         }
 
//         data.datasets[0].data = comp_data;
//         mylineChart.update();
//     })
// }
{% endblock %}
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/javascript.util/0.12.12/javascript.util.min.js"></script>

dbconn/templates/dbconn/test.html
<!DOCTYPE html>
<html>
    <head>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
            <script src="http://cdnjs.cloudflare.com/ajax/libs/javascript.util/0.12.12/javascript.util.min.js"></script>
    </head>

    <body>
        
        <canvas id="myChart" width="1000" height="700"></canvas>
        <button id="sendAjax">button</button>
        

        <!-- 원래 data (label 포함) ajax 통신으로 받아와야 하는데, 우선 하드코딩-->
        <script>
                var data = {
                    labels: [
                    "07.16 00:30", "07.16 01:00", "07.16 01:30", "07.16 02:00"
                    ],
                    datasets: [
                        {
                            label: 'OJVM: Generic/Sec', 
                            data: [
                                "0", "0.14", "0.884", "0.356", 
                            ],
                            backgroundColor: [
                                'rgba(255, 99, 132, 0.2)',
                            ],
                            borderColor: [
                                'rgba(255,99,132,1)',
                            ],
                            borderWidth: 1
                        },
                        {
                            label: 'db file scattered red/Sec',
                            data: [
                                0.776, 0.001, 0, 0.259
                            ],
                            backgroundColor: [
                            'rgba(54, 162, 235, 0.2)',
                            ],

                        },
                        {
                            label: 'Backup: MML create a backup piece/Sec',
                            data: [
                                0, 0.063, 0.535, 0.199
                            ],
                            backgroundColor: [
                            'rgba(255, 206, 86, 0.2)',
                            ],

                        }
                ]
                };

        var options = {
                    animation: {
                        animateScale: true
                    },
                    responsive: false,
                    scales: {
                        yAxes: [
                            {
                                ticks: {
                                    beginAtZero: true                                                                    
                                }
                            }
                        ]
                    }
                };
         
                var ctx = document.getElementById("myChart").getContext('2d');                                           
                var myLinechart = new Chart(ctx, {
                    type: 'line',
                    data: data,
                    options: options
                });

                
                var button = document.getElementById("sendAjax")
 
button.addEventListener("click", function() {
    sendAjax('http://localhost:8000/');
})
 
function sendAjax(url) {
    var oReq = new XMLHttpRequest();
 
    oReq.open('POST', url);
    oReq.setRequestHeader('Content-Type', "application/json") // json 형태로 보낸다                         
    oReq.send();
 
    oReq.addEventListener('load', function() {
        var result = JSON.parse(oReq.responseText);
        var score = result.score;
        var comp_data = data.datasets[0].data;
 
        for (var i = 0; i < comp_data.length; i++) {
            comp_data[i] = score[i];
        }
 
        data.datasets[0].data = comp_data;
        mylineChart.update();
    })
}

        </script>
    </body>
</html>