config/urls.py
from django.contrib import admin
from django.urls import path, include
from dbconn.views import index

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('dbconn/', include('dbconn.urls', namespace="dbconn")),
    path('report/', include('report.urls', namespace="report")),
]

dbconn/urls.py
from django.urls import path
from . import views

app_name = 'dbconn'

urlpatterns = [
    path('create/', views.create_chart, name='create_chart'),
    path('history/', views.HistoryAPIView.as_view(), name='history_list')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}"/>
</head>
<body>
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.js"></script>
  
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  
  <script src="http://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/a549aa8780dbda16f6cff545aeabc3d71073911e/src/js/bootstrap-datetimepicker.js"></script>
  
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" crossorigin="anonymous">
  
  <link href="http://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/a549aa8780dbda16f6cff545aeabc3d71073911e/build/css/bootstrap-datetimepicker.css" rel="stylesheet"/>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/javascript.util/0.12.12/javascript.util.min.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
  <script>
    var csrftoken = Cookies.get('csrftoken');
    function csrfSafeMethod(method) {
      // these HTTP methods do not require CSRF protection
      return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
      beforeSend: function(xhr, settings) {

        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
          xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
      }
    });
    $(document).ready(function(){
      {% block domready %}
      {% endblock %}
       });
  </script>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}

<form method="POST" id="post-form">

  {% csrf_token %}

  <div container="fluid">
  <div class ="container">
    <h1> Connection Info </h1>
    <div class ="formBox">
      <form>
        <div class="row">
          <div class="col-sm-6">
            <div class="inputBox">
              <div class="inputText">User name</div>
              <input id="username" type="text" class="input">
            </div>
          </div>

          <div class="col-sm-6">
            <div class="inputBox">
              <div class="inputText">Password</div>
              <input id="password" type="password" class="input">
            </div>
          </div>
        </div>

        <div class="row">
        <div class="col-sm-6">
          <div class="inputBox ">
            <div class="inputText">Server IP</div>
            <input id="server_ip" type="text" class="input">
          </div>
        </div>

        <div class="col-sm-6">
          <div class="inputBox">
            <div class="inputText">Port #</div>
            <input id="port" type="text" name="" class="input">
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="col-sm-6"> 
          <div class="form-group pmd-textfield pmd-textfield-floating-label">
            <label class="control-label" for="start_date">Start Date</label>
            <input type="text" class="form-control" id="start_date">
          </div>
        </div>
        <div class="col-sm-6"> 
          <div class="form-group pmd-textfield pmd-textfield-floating-label">
            <label class="control-label" for="end_date">End Date</label>
            <input type="text" class="form-control" id="end_date">
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12">
          <input type="submit" class="button" value="post">
        </div>
      </div>
      </form>

      
    </div>
  </div>
</div>



  <!-- <div class="fieldWrapper">
    <label for="username">Username : </label>
    <input id="username"> 
  </div>
  <div class="fieldWrapper">
    <label for="password">Password : </label>
    <input id="password"> 
  </div>
  <div class="fieldWrapper">
    <label for="server_ip">server ip : </label>
    <input id="server_ip"> 
  </div>
  <div class="fieldWrapper">
    <label for="port">port : </label>
    <input id="port"> 
  </div>
  <div class="fieldWrapper">
    <label for="start_date">start date : </label>
    <input id="start_date"> 
  </div>
  <div class="fieldWrapper">
    <label for="end_date">end date : </label>
    <input id="end_date"> 
  </div> -->
  <!-- <input type="submit" value="Post" class="tiny button"> -->
</form>


<a href="#" class="create">등록</a>
<br>
<br>

<div id="history">
</div>
{% endblock %}

<script>
{% block domready %}
  $(".input").focus(function() {
    $(this).parent().addClass("focus");
  })

  $('start_date').datetimepicker();
  
    // End date date and time picker 
  $('end_date').datetimepicker({
      useCurrent: false 
    });
    
    // start date picke on chagne event [select minimun date for end date datepicker]
  $("#start_date").on("dp.change", function (e) {
      $('#end_date').data("DateTimePicker").minDate(e.date);
    });
    // Start date picke on chagne event [select maxmimum date for start date datepicker]
  $("#end_date").on("dp.change", function (e) {
    $('#start_date').data("DateTimePicker").maxDate(e.date);
    });

// https://realpython.com/django-and-ajax-form-submissions/
function create_chart() {
    console.log("create chart is working!") // sanity check
    $.ajax({
      type: "POST",
      url: "{% url 'dbconn:create_chart' %}",
      data : {
        "username": $('#username').val(),
        "password": $('#password').val(),
        "server_ip": $('#server_ip').val(),
        "port": $('#port').val(),
        "start_date": $('#start_date').val(),
        "end_date": $('#end_date').val(),
      },
      success : function(history){
        console.log(history);
        $('#history').append(
          `${history.db_conn} | ${history.start_date} ~ ${history.end_date}<br>`
        );
      },
      error: function(error){
        console.log("error");
        console.log(error);
      }
    })

};


$('#post-form').on('submit', function(event){
    event.preventDefault();
    console.log("form submitted!")  // sanity check
    create_chart();
    
});

$.ajax({
  type: "GET",
  url: "{% url 'dbconn:history_list' %}",
  success: function(data){

    data.map(history => {
        $('#history').append(
          `${history.db_conn} | ${history.start_date} ~ ${history.end_date}<br>`
      )
      });

    ;
  },
  error: function(error){
    console.log("error");
    console.log(error);
  }
})
{% endblock %}
</script>